create table if not exists public.songbattle_battles (
  id bigint generated by default as identity primary key,
  position integer not null unique check (position > 0),
  song_a_title text not null check (length(btrim(song_a_title)) > 0),
  song_a_artist text not null check (length(btrim(song_a_artist)) > 0),
  song_b_title text not null check (length(btrim(song_b_title)) > 0),
  song_b_artist text not null check (length(btrim(song_b_artist)) > 0),
  genre text not null default 'Pop',
  is_active boolean not null default true
);

create table if not exists public.songbattle_results (
  battle_id bigint primary key references public.songbattle_battles(id) on delete cascade,
  votes_a bigint not null default 0 check (votes_a >= 0),
  votes_b bigint not null default 0 check (votes_b >= 0)
);

create table if not exists public.songbattle_votes (
  battle_id bigint not null references public.songbattle_battles(id) on delete cascade,
  voter_id uuid not null,
  choice smallint not null check (choice in (0, 1)),
  created_at timestamptz not null default now(),
  primary key (battle_id, voter_id)
);

alter table public.songbattle_battles enable row level security;
alter table public.songbattle_results enable row level security;
alter table public.songbattle_votes enable row level security;

drop policy if exists "Public can read active Songbattle pairs" on public.songbattle_battles;
create policy "Public can read active Songbattle pairs"
  on public.songbattle_battles for select to anon, authenticated
  using (is_active);

drop policy if exists "Public can read Songbattle totals" on public.songbattle_results;
create policy "Public can read Songbattle totals"
  on public.songbattle_results for select to anon, authenticated
  using (true);

revoke all on public.songbattle_battles, public.songbattle_results, public.songbattle_votes
  from public, anon, authenticated;
grant select on public.songbattle_battles, public.songbattle_results to anon, authenticated;

create or replace function public.get_songbattle_state(p_voter_id uuid)
returns table (
  id bigint,
  battle_position integer,
  song_a_title text,
  song_a_artist text,
  song_b_title text,
  song_b_artist text,
  genre text,
  votes_a bigint,
  votes_b bigint,
  my_choice smallint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    b.id,
    b.position,
    b.song_a_title,
    b.song_a_artist,
    b.song_b_title,
    b.song_b_artist,
    b.genre,
    coalesce(r.votes_a, 0)::bigint,
    coalesce(r.votes_b, 0)::bigint,
    v.choice
  from public.songbattle_battles as b
  left join public.songbattle_results as r on r.battle_id = b.id
  left join public.songbattle_votes as v
    on v.battle_id = b.id and v.voter_id = p_voter_id
  where b.is_active
  order by b.position;
$$;

create or replace function public.cast_songbattle_vote(
  p_battle_id bigint,
  p_choice smallint,
  p_voter_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_rows integer;
begin
  if p_voter_id is null or p_choice is null or p_choice not in (0, 1) then
    raise exception 'Invalid vote';
  end if;

  if not exists (
    select 1 from public.songbattle_battles
    where id = p_battle_id and is_active
  ) then
    raise exception 'Battle not found or inactive';
  end if;

  insert into public.songbattle_votes (battle_id, voter_id, choice)
  values (p_battle_id, p_voter_id, p_choice)
  on conflict (battle_id, voter_id) do nothing;

  get diagnostics inserted_rows = row_count;
  if inserted_rows = 0 then
    return false;
  end if;

  insert into public.songbattle_results (battle_id, votes_a, votes_b)
  values (
    p_battle_id,
    case when p_choice = 0 then 1 else 0 end,
    case when p_choice = 1 then 1 else 0 end
  )
  on conflict (battle_id) do update
    set votes_a = public.songbattle_results.votes_a + excluded.votes_a,
        votes_b = public.songbattle_results.votes_b + excluded.votes_b;

  return true;
end;
$$;

revoke all on function public.get_songbattle_state(uuid) from public;
revoke all on function public.cast_songbattle_vote(bigint, smallint, uuid) from public;
grant execute on function public.get_songbattle_state(uuid) to anon, authenticated;
grant execute on function public.cast_songbattle_vote(bigint, smallint, uuid) to anon, authenticated;

insert into public.songbattle_battles
  (position, song_a_title, song_a_artist, song_b_title, song_b_artist, genre)
values
  (1, 'Blinding Lights', 'The Weeknd', 'Levitating', 'Dua Lipa', 'Synth-pop / Disco-pop'),
  (2, 'As It Was', 'Harry Styles', 'good 4 u', 'Olivia Rodrigo', 'Pop / Pop-rock'),
  (3, 'Get Lucky', 'Daft Punk', 'Flowers', 'Miley Cyrus', 'Disco / Pop')
on conflict (position) do nothing;

insert into public.songbattle_results (battle_id)
select id from public.songbattle_battles
on conflict (battle_id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'songbattle_results'
  ) then
    alter publication supabase_realtime add table public.songbattle_results;
  end if;
end
$$;
